name: Release

on:
  push:
    tags: ['v*']

permissions:
  contents: write
  packages: write

jobs:
  build:
    name: Build & Release Binaries
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true
      - name: Build Linux Binary
        run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-w -s" -o filetolink-go-linux-amd64 .
      - name: Build Windows Binary
        run: CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -ldflags="-w -s" -o filetolink-go-windows-amd64.exe .
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            filetolink-go-linux-amd64
            filetolink-go-windows-amd64.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
